apiVersion: v1
entries:
  mrc:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-10-02T10:07:53.4481936Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 241ffbbf10f52262eb36a8a078cd17cda64673c65cdc3081af23ccd5b687004e
    home: mrc.zaakonline.nl
    icon: mrc.zaakonline.nl
    name: mrc
    urls:
    - mrc-0.1.0.tgz
    version: 0.1.0
generated: "2020-10-02T10:07:53.4281351Z"
